### ISSUE TITLE
Issues in Setting Up the theme is iTerm2

### ISSUE THREAD

**Issue by rohittm** [ahmadawais/Shades-of-Purple-iTerm2#1]
@ahmadawais Let me know if I'm missing something. So, here are the steps I did:

 ✅ Drop the shades-of-purple.zsh-theme file in to the ~/.oh-my-zsh/themes/ directory.
![screen shot 2018-04-03 at 18 52 07](https://user-images.githubusercontent.com/3204558/38251817-24f7715e-3770-11e8-80b7-16de0df5fe6e.png)

✅Open up your ZSH preferences at ~/.zshrc and change the theme variable to ZSH_THEME="shades-of-purple".
![screen shot 2018-04-03 at 18 53 28](https://user-images.githubusercontent.com/3204558/38251900-546b7afc-3770-11e8-8515-35bd13c9400a.png)

✅ In iTerm2 access the Preferences pane on the Profiles tab.

✅ Under the Colors tab import the shades-of-purple.itermcolors file via the Load Presets drop-down at the bottom right.
![screen shot 2018-04-03 at 18 54 29](https://user-images.githubusercontent.com/3204558/38251949-775627ce-3770-11e8-9339-480698f4d01f.png)

✅ Under the Text tab change the font for each type (Regular Font to Operator Mono or Fira Code or whatever you like, but for Non-ASCII font you must use Inconsolata for Powerline.
![screen shot 2018-04-03 at 18 54 58](https://user-images.githubusercontent.com/3204558/38251986-8def0fe6-3770-11e8-8b1b-ef53e4b8399a.png)

✅ Refresh ZSH by typing source ~/.zshrc on the command line.
![screen shot 2018-04-03 at 18 55 58](https://user-images.githubusercontent.com/3204558/38252020-ac4ca6b0-3770-11e8-8240-8513258c1e98.png)

❌ Done!!! 🙌

The Non ASCII Characters aren't showing up 😢
![screen shot 2018-04-03 at 18 57 10](https://user-images.githubusercontent.com/3204558/38252078-d7ffa12c-3770-11e8-848f-09e12c8aa524.png)

**Comment by ahmadawais** [comment]
@rohittm thanks for the detailed issue. Those missing characters are contributed by the non ASCII Font option and that's where Powerline fonts work. Also I am using Inconsolata not the bold version. 

![image](https://on.ahmda.ws/qcUb/c)

Try that and reboot your system.

Check this

![image](https://on.ahmda.ws/qbu4/c)

**Comment by ahmadawais** [comment]
Here's the proof that your powerline fonts are wrong.

Check

![image](https://on.ahmda.ws/qcOt/c)

**Comment by rohittm** [comment]
@ahmadawais Thanks a lot for the response. That was exactly what I did wrong. Changed to medium, instead of bold now. Working perfectly fine  😊
![screen shot 2018-04-03 at 20 01 15](https://user-images.githubusercontent.com/3204558/38255632-f423bfba-3779-11e8-9f4b-1c0e01f790db.png)

Nice theme. I share the love for 💜 purple as well.

**Comment by ahmadawais** [comment]
Awesome. Glad to help. 💜
