### ISSUE TITLE
How to get rid of the cross on each terminal line?

### ISSUE THREAD

**Issue by montoulieu** [ahmadawais/Shades-of-Purple-iTerm2#4]
I love the theme, but as an atheist, I'm not a fan of the Jesus cross at the beginning of every line I type into iTerm.
Any way to get rid of this or maybe customize it to a pentagram? 😜

**Comment by ahmadawais** [comment]
Thanks. What cross? Image?

**Comment by montoulieu** [comment]
Thanks for the fast response Ahmad, was trying to upload one to my original post but it was failing.
Here's an imgur link:
https://imgur.com/a/FeOriBU

**Comment by ahmadawais** [comment]
You can change it at the end of this line

https://github.com/ahmadawais/Shades-of-Purple-iTerm2/blob/master/shades-of-purple.zsh-theme#L75

When I get time, I'll do that myself. I didn't want to make this theme connected to any religion. That part came out of the fork. I'll make the theme neutral.

**Comment by montoulieu** [comment]
Nice! Thanks for that and I appreciate your help on it.
I'm all for the separation between church and command line. 🖖

**Comment by ahmadawais** [comment]
@montoulieu no worries. I just released a major new version. This should now be fixed.

https://github.com/ahmadawais/Shades-of-Purple-iTerm2/releases/tag/2.0.0

**Comment by ahmadawais** [comment]
I don't mean any disrespect to any religion by this. I just don't want to mix this or enforce anything else on terminal theme. So, yeah we are all good.
